- name: Example playbook
  hosts: centos1
  gather_facts: false
  tasks:
    - name: Set a custom fact
      set_fact:
        custom_fact: This is a custom fact
    - name: Print the custom fact
      debug:
        msg: "{{ custom_fact }}"
