- hosts: all
  tasks:
    - name: Jinja2 for loop
      debug:
        msg: >
          {% for entry in ansible_all_ipv4_addresses -%}
            IPv4 address {{ loop.index }} = {{ entry }}
          {% endfor %}
