- name: Example playbook
  hosts: centos1
  become: true
  tasks:
    - name: Create multiple users
      user:
        name: "{{ item.key }}"
        comment: "{{ item.value.comment }}"
      with_dict:
        john:
          comment: This is John
        mary:
          comment: This is Mary
