- hosts: all
  tasks:
    - name: Jinja2 if/else statement
      debug:
        msg: >
          {# This is a comment in Jinja2 -#}
          {% if ansible_distribution == "CentOS" -%}
            This is one of CentOS VMs - {{ ansible_hostname }}
          {% else -%}
            This is one of Ubunut VMs - {{ ansible_hostname }}
          {% endif %}
