- hosts: all
  gather_facts: false
  tasks:
    - name: 1st sleep
      command: sleep 5
      when: inventory_hostname == 'provisioner'
    - name: 2nd sleep
      command: sleep 5
      when: inventory_hostname == 'centos1'
    - name: 3rd sleep
      command: sleep 5
      when: inventory_hostname == 'ubuntu1'
    - name: 4th sleep
      command: sleep 5
      when: inventory_hostname == 'provisioner'
    - name: 5th sleep
      command: sleep 5
      when: inventory_hostname == 'centos1'
