---
# Each Ansible playbook starts with a '-',
# which means that Ansible expects the user
# to pass an array of arguments.

# The first section describes how the connection
# to the target remotes should be executed.
# Here, the user can define a wide variety of
# parametrs. Most notably, the: name of the playbook,
# target hosts inventory group, privilege escalation
# and playbook wide variables.
- name: Example playbook
  hosts: all
  # The 'tasks' section represents the list of tasks
  # that will be executed on the remote hosts.
  tasks:
    - name: Example task
      command: whoami
      notify: whoami_handler
  handlers:
    - name: whoami_handler
      debug:
        msg: 'Whoami was called on {{ ansible_hostname }}'
...
