- name: Example playbook
  hosts: all
  become: true
  tasks:
    - name: Set SSH message of the day (motd)
      copy:
        content: "Host system: {{ item }}\n"
        dest: /etc/motd
      notify: Set MOTD
      with_items:
        - CentOS
        - Ubuntu
      when: ansible_distribution == item
  handlers:
    - name: Set MOTD
      debug:
        msg: The MOTD was set
