---
# Each Ansible playbook starts with a '-',
# which means that Ansible expects the user
# to pass an array of arguments.

# The first section describes how the connection
# to the target remotes should be executed.
# Here, the user can define a wide variety of
# parametrs. Most notably, the: name of the playbook,
# target hosts inventory group, privilege escalation
# and playbook wide variables.
- name: Example playbook
  hosts: provision
  fact_path: "{{ playbook_dir }}/files"
  # The 'tasks' section represents the list of tasks
  # that will be executed on the remote hosts.
  tasks:
    - debug:
        msg: "{{ ansible_local.samplefacts1.kernel_package }}"
    - debug:
        msg: "{{ ansible_local.samplefacts2.kernel_package.package }}"
...
