---
centos:
  hosts:
    centos1:
      ansible_host: '192.168.77.21'
    centos2:
      ansible_host: '192.168.77.22'
    centos3:
      ansible_host: '192.168.77.21'
ubuntu:
  hosts:
    ubuntu1:
      ansible_host: '192.168.77.23'
    ubuntu2:
      ansible_host: '192.168.77.24'
    ubuntu3:
      ansible_host: '192.168.77.23'
...
