---
- hosts: all
  become: true
  tasks:
    - name: Send reboot signal to all hosts
      shell: sleep 2 && reboot
      async: 1
      poll: 0
    - name: Wait for hosts to become responsive
      wait_for_connection:
        connect_timeout: 20 
        sleep: 10
        delay: 20
        timeout: 300
...