centos:
  hosts:
    provisioner:
      ansible_connection: local
    centos1:
      ansible_host: '192.168.77.22'
      ansible_port: 2345
ubuntu:
  hosts:
    ubuntu1:
      ansible_host: '192.168.77.23'
linux:
  children:
    centos:
    ubuntu:
  vars:
    ansible_become: true
