---
- hosts: all
  tasks:
    - name: 1st sleep
      command: sleep 20
      when: ansible_hostname == 'centos1'
      async: 45
      poll: 0
      register: out1
    - name: 2nd sleep
      command: sleep 5
      when: ansible_hostname == 'centos2'
      async: 10
      poll: 0
      register: out2
    - name: 3rd sleep
      command: sleep 5
      when: ansible_hostname == 'ubuntu1'
      async: 10
      poll: 0
      register: out3
    - name: 4th sleep
      command: sleep 5
      when: ansible_hostname == 'ubuntu2'
      async: 10
      poll: 0
      register: out4
    - name: 5th sleep
      command: sleep 5
      when: ansible_hostname == 'centos1'
      async: 10
      poll: 0
      register: out5
    - name: Show result
      debug:
        var: out1
    - name: Show result in Jinja2 format
      debug:
        msg: "{{ out1 }}"
...