---
# Each Ansible playbook starts with a '-',
# which means that Ansible expects the user
# to pass an array of arguments.

# The first section describes how the connection
# to the target remotes should be executed.
# Here, the user can define a wide variety of
# parametrs. Most notably, the: name of the playbook,
# target hosts inventory group, privilege escalation
# and playbook wide variables.
- name: Example playbook
  hosts: centos2
  become: true
  # The 'tasks' section represents the list of tasks
  # that will be executed on the remote hosts.
  tasks:
    - name: Create facts.d directory on remote hosts
      file:
        state: directory
        recurse: yes
        path: /etc/ansible/facts.d
    - name: Copy the custom facts
      copy:
        src: samplefacts1.fact
        dest: /etc/ansible/facts.d/kernel.fact
        owner: root
        group: root
        mode: 0755
    - name: Re-run setup
      setup:
        filter: ansible_local
...
