---
control:
  hosts:
    ansible:
      ansible_connection: local
centos:
  hosts:
    centos1:
      ansible_port: 2345
    centos2:
  vars:
    ansible_user: root
ubuntu:
  hosts:
    ubuntu1:
    ubuntu2:
  vars:
    ansible_become: true
linux:
  children:
    centos:
    ubuntu:
...
