---
# Each Ansible playbook starts with a '-',
# which means that Ansible expects the user
# to pass an array of arguments.

# The first section describes how the connection
# to the target remotes should be executed.
# Here, the user can define a wide variety of
# parametrs. Most notably, the: name of the playbook,
# target hosts inventory group, privilege escalation
# and playbook wide variables.
- name: Example playbook
  hosts: linux
  become: true
  gather_facts: false
  environment:
    http_proxy: http://10.144.1.10:8080
    https_proxy: http://10.144.1.10:8080
  # The 'tasks' section represents the list of tasks
  # that will be executed on the remote hosts.
  tasks:
    - name: Run yum clean
      command: yum clean all
      when: ansible_distribution == "CentOS"
    - name: Delete /var/cache/yum
      file:
        path: /var/cache/yum
        state: absent
      when: ansible_distribution == "CentOS"
    - name: Update all packages
      yum:
       name: '*'
       state: latest
      when: ansible_distribution == "CentOS"
...
