---
provision:
  hosts:
    ansible:
      ansible_connection: local
centos:
  hosts:
    centos1:
      ansible_host: '192.168.77.21'
    centos2:
      ansible_host: '192.168.77.22'
  vars:
    ansible_user: root
ubuntu:
  hosts:
    ubuntu1:
      ansible_host: '192.168.77.23'
    ubuntu2:
      ansible_host: '192.168.77.24'
...
