---
centos:
  hosts:
    centos1:
      ansible_connection: local
      ansible_user: vagrant
    centos2:
      ansible_host: '192.168.77.22'
ubuntu:
  hosts:
    ubuntu1:
      ansible_host: '192.168.77.23'
    ubuntu2:
      ansible_host: '192.168.77.24'
...
