centos:
  hosts:
    provisioner:
      ansible_connection: local
      unique_hash: "NDRhOTBlZmU3OTc2"
    centos1:
      ansible_host: '192.168.77.22'
      ansible_port: 2345
      unique_hash: "MzI0ZTU2ZWMxNTkz"
ubuntu:
  hosts:
    ubuntu1:
      ansible_host: '192.168.77.23'
      unique_hash: "YjlkYTdlMjYyYTU3"
